######################## default configuration ####################
baseURL = "http://examplesite.org"
title = "Inline Industries Inc."
theme = "educenter-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################## navigation ###############################

# main menu
[[menu.main]]
weight = 1
name = "About"
URL = "about"

[[menu.main]]
weight = 2
name = "products"
hasChildren = true

  [[menu.main]]
  parent = "products"
  name = "products_available"
  URL = "available-products"

  [[menu.main]]
  parent = "products"
  name = "new_used"
  URL = "new-and-used-equipment"

[[menu.main]]
weight = 3
name = "parts_and_services"
URL = "parts-and-services"

# [[menu.main]]
# weight = 4
# name = "Pages"
# hasChildren = true

#   [[menu.main]]
#   parent = "Pages"
#   name = "teacher"
#   URL = "teacher"

#   [[menu.main]]
#   parent = "Pages"
#   name = "notice"
#   URL = "notice"

#   [[menu.main]]
#   parent = "Pages"
#   name = "event"
#   URL = "event"

#   [[menu.main]]
#   parent = "Pages"
#   name = "scholarship"
#   URL = "scholarship"

#   [[menu.main]]
#   parent = "Pages"
#   name = "research"
#   URL = "research"

# [[menu.main]]
# name = "blog"
# URL = "blog"
# weight = 4

[[menu.main]]
name = "contact_info"
URL = "contact"
weight = 5


# footer menu

# [[menu.footer]]
# name = "teacher"
# URL = "teacher"

[[menu.footer]]
name = "Tremcar"
URL = "tremcar"

# [[menu.footer]]
# name = "event"
# URL = "event"

# [[menu.footer]]
# name = "scholarship"
# URL = "scholarship"

# [[menu.footer]]
# name = "research"
# URL = "research"


#################### default parameters ################################
[params]
logo = "images/Inline-Industries-logo-outline.png"
# Meta data
description = "We specialize in all types of transportation vessels. This includes Food Grade, Milk, Sugar, Juice, Dangerous Goods, Chemical, Acid, Vacuum, Septic, Pneumatic, and Dry Bulk."
author = "Inline Industires Inc."
# contact info
address = "6727 68 Ave Edmonton, Alberta. T6E 3E3"
tollfree = "1-866-999-3931"
mobile = "780-463-3931"
email = "intanks@telus.net"
# contact form action
contact_form_action = "https://formspree.io/f/xyybkvrn" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.svg" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "" # replace this url with yours
mailchimp_form_name = "" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################
# themify icon : https://themify.me/themify-icons
# [[params.social]]
# title = "facebook"
# icon = "ti-facebook"
# link = "#"

# [[params.social]]
# title = "twitter"
# icon = "ti-twitter-alt"
# link = "#"

# [[params.social]]
# title = "instagram"
# icon = "ti-instagram"
# link = "#"

# [[params.social]]
# title = "github"
# icon = "ti-github"
# link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin"
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 Inline Industries Inc."


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2020 Inline Industries Inc."